name: CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image (commit tag)
              run: |
                  docker build \
                    -t cloud-native-devops-app:${{ github.sha }} \
                    -f docker/Dockerfile .

            - name: Tag Docker image as latest
              run: |
                  docker tag \
                    cloud-native-devops-app:${{ github.sha }} \
                    cloud-native-devops-app:latest
